services:
  bankerchief:
    image: docker.io/library/caddy:alpine
    container_name: bankerchief
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/srv
      - ./data:/transactions
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
